import 'react'
import ServiceAutoGeneratedGuideGuide from '../../components/ServicePage/AutoGeneratedGuide'

export default function AutoGeneratedGuide () {
  return (
    <ServiceAutoGeneratedGuideGuide />
  )
}
