import { RouterProvider, createBrowserRouter } from 'react-router-dom'
import Root from './routes/root'
import Catalog from './routes/catalog'
import Service from './routes/service'
import Methods from './routes/service/methods'
import AutoGeneratedGuide from './routes/service/autoGeneratedGuide'

const router = createBrowserRouter([
  {
    path: '/',
    element: <Root />,
    children: [
      {
        path: '/:rootServiceId/service/:serviceId',
        element: <Service />,
        children: [
          {
            path: '/:rootServiceId/service/:serviceId/guide/auto',
            element: <AutoGeneratedGuide />
          },
          {
            path: '/:rootServiceId/service/:serviceId/',
            element: <Methods />
          }
        ]
      },
      {
        path: '/:rootServiceId',
        element: <Catalog />
      },
      {
        path: '/',
        element: <Catalog />
      }
    ]
  }
])

function App () {
  return (
    <RouterProvider router={router} />
  )
}

export default App
